// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TicTacToe.DataSource.Models;

#nullable disable

namespace TicTacToe.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250610155649_RemovedPrimaryId2")]
    partial class RemovedPrimaryId2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TicTacToe.DataSource.Models.CurrentGameDTO", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("text");

                    b.Property<int>("PlayerO")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerX")
                        .HasColumnType("integer");

                    b.ComplexProperty<Dictionary<string, object>>("GameBoard", "TicTacToe.DataSource.Models.CurrentGameDTO.GameBoard#GameBoardDTO", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int[,]>("Field")
                                .IsRequired()
                                .HasColumnType("integer[]");
                        });

                    b.HasKey("Uuid");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("TicTacToe.DataSource.Models.UserDTO", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Uuid");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
